name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: cmake create project
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: build cmake project
      run: cmake --build build --config Release
    - name: execute test
      run: ctest --test-dir build --build-config Release --output-on-failure
